import axios from 'axios';
import config from '../config.cjs';

const imagine = async (m, gss) => {
  const prefix = config.PREFIX;
  const body = m.body || "";
  const cmd = body.startsWith(prefix)
    ? body.slice(prefix.length).split(" ")[0].toLowerCase()
    : "";

  // Command triggers
  if (cmd !== "imagine" && cmd !== "draw" && cmd !== "aiimg") return;

  try {
    const prompt = body.slice(prefix.length + cmd.length).trim();

    if (!prompt) {
      return m.reply("🎨 *Please provide a description!*\n\n*Example:* .imagine a futuristic car in neon city");
    }

    // Inform the user that the "artist" is working
    await m.reply("_🎨 Creating your masterpiece, please wait..._");

    // API Endpoint for Text-to-Image
    const apiUrl = `https://api-faa.my.id/faa/ai-text2img-pro?prompt=${encodeURIComponent(prompt)}`;

    // Send the generated image directly
    // Most AI image APIs return the image file itself
    await gss.sendMessage(m.from, {
      image: { url: apiUrl },
      caption: `✨ *Prompt:* ${prompt}\n\n*Generated by Gemini AI*`
    }, { quoted: m });

  } catch (error) {
    console.error("IMAGINE CMD ERROR:", error);
    m.reply("⚠️ *System Error:* The image generator is currently overloaded. Try again later.");
  }
};

export default imagine;
